### ISSUE TITLE
Ellipsis should be added if cell content is too long

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#184]
See http://jsfiddle.net/tsvr92ge/
The cell contents for "Child 1 with a really long name" overflow the available widths. It would be nice if an ellipsis could be added (maybe optionally via a column setting) in those cases.
I managed to get it to work for the added columns (see commented CSS) but not for col-0. You'd probably have to compute explicit widths for the anchors to get that to work.

**Comment by QueroBartK** [comment]
@jochenberger I've just done a fiddle with only a jstree (no grid): [fiddle](https://jsfiddle.net/n0rduyfd/4/)
you can see that I've tried containing the text in the div I used to initialize the tree with by setting the width (which did nothing) and I've even tried using an outer div (this contained it but didn't add the Ellipsis). So maybe we should first try to get this in jstree itself before adding it to the grid plugin?

**Comment by jochenberger** [comment]
@QueroBartK: err, you did notice that you wrote `overflox` in your CSS instead of `overflow`, didn't you? ;-)

**Comment by QueroBartK** [comment]
@jochenberger in one of my previous verisons I did indeed but it should be fixed in this fiddle. either way it didn't give us the result we wanted.

**Comment by deitch** [comment]
oh, I don't know. I think `overflox` would be cool! :-)

So let me understand this. There are 2 issues:

1. Overflow in a grid cell. This is handled with the CSS via the @jochenberger fiddle
2. Overflow in the root tree. This is not yet solved.

Is that right?

**Comment by QueroBartK** [comment]
Yes, the cells without the tree can be handled by @jochenberger 's css.

The problem remains in with the tree itself though. As at the moment I can't find some css that works (and doesn't totally screw up the tree.). I think this is the biggest hurdle for implementing this. But since this has to do with the tree itself I feel like it it would be better to create this issue in jstree itself and once this is resolved resolve it for the grid.

**Comment by QueroBartK** [comment]
I've opened an issue in jstree for this: [https://github.com/vakata/jstree/issues/1594](https://github.com/vakata/jstree/issues/1594)

**Comment by deitch** [comment]
> Yes, the cells without the tree can be handled by @jochenberger 's css.

Great. Do you want to create a PR for this, @jochenberger ? We can merge it in and at least handle the cells case. Then we can close this in favour of the PR and the jstree issue.

**Comment by QueroBartK** [comment]
Ok, I've actually found some css that will work (as I posted in the jstree issue) So this would result in the following [fiddle](http://jsfiddle.net/tsvr92ge/1/)

**Comment by jochenberger** [comment]
Sorry, I won't find the time to do a PR today, maybe I'll manage come up with one by the end of the week.
By the way, I'm not sure if I like the `calc` solution. It's not really maintainable and uses magic numbers. If @vakata or @deitch decide to change some internal styling, the display will be off.

**Comment by QueroBartK** [comment]
@jochenberger I don't think you can solve this problem in pure css without using `calc`. so if you don't want to use calc then we'll have to use some javascript in which case I should probably reopen my issue in jstree. There is also the problem in css that although you see the Ellipsis to know you have more text if you add a scrollbar to see the rest of the text you'll won't see anything (unless you're using firefox which seems to be the only browser supporting this behaviour)

**Comment by QueroBartK** [comment]
Also my current suggested solution doesn't immediately provide a way to add a scrollbar (should that be what you wanted to use) on the entire tree column. This is because the overflow is contained in the node and thus not noticed by parent html elements of that node.

**Comment by QueroBartK** [comment]
@jochenberger if you really want you could always write some css with the values in the calc that overrides the default css. That way you control the values.

**Comment by jochenberger** [comment]
I actually don't care if the text is not completely visible, I would just like the ellipsis as an indicator that it isn't.

**Comment by deitch** [comment]
> Sorry, I won't find the time to do a PR today, maybe I'll manage come up with one by the end of the week.

Thanks. I have no time to get one now either. :-)

**Comment by deitch** [comment]
> By the way, I'm not sure if I like the calc solution. It's not really maintainable and uses magic numbers. If @vakata or @deitch decide to change some internal styling, the display will be off.

I struggled with that many times over the years. That is why we made the major switch from `<div>` based to `table` based years back. Created new problems, but the width was just insanely impossible. You never could get the edge cases right, and more and more it felt like edge cases where actually the ones that worked, while the majority did not!

I think, correct me if I am wrong, that the first column is more of a jstree question. To be fair, Ivan could say, "look, jstree doesn't support overflow text", but he probably won't. But I think it should be a jstree issue, unless there is something in it that makes it an issue solely when the grid is there but not with native jstree?

**Comment by QueroBartK** [comment]
@vakata just answered the issue: https://github.com/vakata/jstree/issues/1594

> Sorry, but I do not plan on adding such functionality.
> 
> All systems I have seen either cut off the text (without an ellipsis) and let you resize the tree container or provide a horizontal scrollbar on the tree container - jstree supports both those scenarios.
> 
> Quite frankly - I do not see the need for it - can you provide a screenshot of a tree that uses this (OS file manager, or something else), as I can't even imagine a good implementation. The idea of cutting off using ellipsis and still allowing resizing or scrolling is counter intuitive for me. As for cutting off and not providing a means of resizing - it would be very confusing for the user as whole levels of the tree will be unaccessible, but still - if you need that you can use your calc solution - kudos for that!
> 
> I am closing this for now, but feel free to share any ideas and / or implementation - if something good comes from the discussion I will reopen.
> 
> regards,
> Ivan

Currently it seems like it is not going to be implemented unless one you have a very good reason that can convince him. I can't immediately think of one.

> By the way, I'm not sure if I like the calc solution. It's not really maintainable and uses magic numbers. If @vakata or @deitch decide to change some internal styling, the display will be off.

I was thinking about this. Like I said before you could just override the necessary styles yourself and if you use a css precompiler like sass or less you can actually put these magic numbers in variables. (in the future native css might also have variables: [https://developer.mozilla.org/en-US/docs/Web/CSS/var](https://developer.mozilla.org/en-US/docs/Web/CSS/var))

**Comment by deitch** [comment]
So Ivan won't do it. Understood.

1. Do we still want it in the grid cells?
2. Do we want to override? I really am wary of the `calc` solution, as it feels like asking for incompatibility troubles ahead.

**Comment by QueroBartK** [comment]
@deitch I don't think the calc and the override idea is something we want to put into jsgrid itself. I'm just saying that if someone was using it for themselves they could do this as this feels specific for a certain project.

**Comment by deitch** [comment]
So where does this leave us? If it will not be in jstree, do we still want ellipsis in grid?

**Comment by QueroBartK** [comment]
Personally I would say that it is best to follow Ivan's lead in this and thus not put it in the grid. Maybe @jochenberger has a reason why it might be good enough to have it in the grid but not in the tree.

**Comment by jochenberger** [comment]
My main reason is that it just doesn't look very nice if the text is just cut off and the next column starts right next to it.
Actually, the file manager that @vakata mentioned in vakata/jstree#1594 is a pretty good example. At least *my* file managers (`nemo` as well as `thunar`) do exactly that.
Maybe the missing information for him is that we are talking about a grid view and not only a "simple" tree with a single "column".

**Comment by jochenberger** [comment]
![file-manager](https://cloud.githubusercontent.com/assets/370733/19558998/b271d406-96cd-11e6-882e-6af6b495cfe8.png)
That's about what I'm trying to achieve.

**Comment by jochenberger** [comment]
I think that for this to work, the `width` style of the `a.jstree-grid-col-0` has to be set explicitly. The plugin could do that in the `prepare_grid` function, something like `node.style.width = col_0_width - LEVELINDENT * getLevel(currentItem) + 'px'`. I'll need to dig in deeper.

**Comment by deitch** [comment]
> My main reason is that it just doesn't look very nice if the text is just cut off and the next column starts right next to it.

That image really does highlight it. But I think we need to look at them as 2 separate issues. If @vakata thinks a width-limited jstree does not need an ellipsis for nodes that extend past the edge, that is his choice. We can, however, implement in the treegrid per #188.

> I think that for this to work, the width style of the a.jstree-grid-col-0 has to be set explicitly

You mean for the CSS to do it correctly?

**Comment by jochenberger** [comment]
Yes. If the column had a width set, things should work (see http://jsfiddle.net/tsvr92ge/5/). The width of `100px` is just a semi-random approximation to show how it would look though.

**Comment by QueroBartK** [comment]
well if you do add the option to add ellipsis than you should be wary of the issue with scrollbars: [http://quirksmode.org/css/user-interface/textoverflow.html](http://quirksmode.org/css/user-interface/textoverflow.html)

Even though @jochenberger says he doesn't need it I feel that if it is implemented in jsgrid it should allow for both the use case with and without scrollbars which might be difficult.

**Comment by vakata** [comment]
@jochenberger I see what you mean - thanks for the screenshot. Basically it is the scenario where there is no vertical scrollbar, but you don't want the text to be cut off. Unfortunately I do not see a way to achieve this in pure (but solid and cross-browser) CSS. I will see if I can come up with something and add it as an optional plugin, but I doubt I will come up with something very elegant.

**Comment by deitch** [comment]
@jochenberger :

> If the column had a width set, things should work

I see that from the fiddle. Given, however, that we set the width anyways using the `column` property, interesting that it does not work unless explicit CSS, even though we set the `width` on the column, especially if we resize it.

**Comment by deitch** [comment]
@vakata (I really have to find out one of these days how "Ivan Bozhanov" became "vakata" :-) ):

> if the calc solution is added in the theme file the numbers will no longer be "magic" numbers, which only leaves IE out of the picture, which I can live with

Oh, that is nice. We have gotten so used to layering on that just making it part of the theme simply didn't occur as a suggestion.

So how about that as an approach?

1. `calc` part of the jstree theme so eminently maintainable
2. ellipsises ("ellipsi"?) in grid provided by simple CSS

I will merge the second in as soon as we have a PR.

**Comment by QueroBartK** [comment]
This will still be an optional thing right? I'm asking as I'm a bit afraid that it might have unwanted side affects when used with scrollbars and I do think there are people out there using it with scrollbars.

In order to make it optional it could be as simple as adding the correct css class to the root div.

**Comment by deitch** [comment]
> optional thing

You make a good point. So do you suggest making it a flag to the settings? Or just docs that tell users how to add a css class? I think a flag, but what are your thoughts?

**Comment by QueroBartK** [comment]
Personally I would also go with some flag in the settings. Don't know what @vakata  thinks about this. If he adds a flag then the jstree-grid could just use the same flag as jstree.

**Comment by deitch** [comment]
I love the idea of leveraging the official jstree flag!

**Comment by vakata** [comment]
@deitch - now that you mentioned it - I haven't changed anything in my profile, oh well ... :)
As for my idea - I think of hiding this option under a CSS class (I will use @jochenberger's solution) and adding a core option which will add this class and it will be optional and will default to `false` (in order to be backwards compatible).
How do you guys feel about that?

**Comment by deitch** [comment]
> How do you guys feel about that?

Warm and fuzzy! No, seriously, makes a ton of sense. What's the flag?

**Comment by vakata** [comment]
I just added the `core.themes.ellipsis` option with a few helper functions (`hide_ellipsis`, `show_ellipsis` and `toggle_ellipsis`), but I changed the CSS from the fiddle a bit, so I will wait for @jochenberger to confirm the result, before I release the next patch version.

**Comment by vakata** [comment]
Since the setting can be set at runtime I guess you may want to monitor those method calls (unless the options for the tree and the grid will be separate which could make sense as well). Anyway - you can check the internal variable `_data.core.themes.ellipsis` to see if they are on or off.

**Comment by jochenberger** [comment]
If we just use the existing setting, that would mean that we can only toggle the ellipsis feature for all columns at once and not on a per-column basis, right?
I'd like to be able to control each column's behavior independently, but that would probably lead to some very complicated use cases, especially when `get/set/toggle_ellipsis` comes into play.

**Comment by deitch** [comment]
So `core.themes.ellipsis` option only gives the _initial_ setting, while the `(hide_|show_|toggle)_ellipsis` change the internal variable `_data.core.themes.ellipsis`. 

Are there any ellipsis events for which we should monitor? Case I am thinking of is if someone sets `core.themes.ellipsis=true`, then calls `hide_ellipsis` and it will change in the tree and not the grid.

Overall, I am not too worried, since it is highly unlikely someone will change the setting after the initial load, but you just _know_ that someone will open an issue on that in 3 months when we all have forgotten how to deal with it.

**Comment by vakata** [comment]
Currently there is no event for that (as there is no event for hide/show/toggle icons or dots). 

I see 3 options:
1) I can add those events if you'd like
2) you can override the methods, call the parent methods and apply changes to the grid
3) the grid / tree settings may be unrelated, meaning that you won't care about the state of the tree, as you would only care for the table cells, because I might want cells with ellipsis, but a tree with a vertical scrollbar (if that is possible).

Personally I believe 3) is the best option - that will ensure that the cell and tree CAN be consistent but I will be able to choose different combinations. If that is not what you need I am good to go with 1)

Let me know what you think, I will make the appropriate changes and publish the new patch version.

**Comment by deitch** [comment]
My personal view is that 1 is best, because I like the idea of clean, single interface. If ellipsis is enabled in the tree, it is everywhere; disabled in the tree, disabled everywhere. 

I have done 2 for other things but really dislike it. I prefer loose coupling rather than getting inside the actual stack.

But someone here probably will say we should support separate "ellipsizing" (I don't think that word appears in the OED).

How about the following? Let's add the events to jstree. We will start with ellipsis setting in the grid tracking the setting in the tree.

Then, when someone is ready, we will create a PR to optionally separate them. But that does get us past first stage (and stops bothering you). 

In any case, I prefer at the very least an option to have them synchronized (actually, the default), and events give us the ability to do that. Then, if we want, we can add a grid option to override 

* `grid.ellipsis === true` - always show ellipsis in grid
* `grid.ellipsis === false` - never show ellipsis in grid
* `grid.ellipsis === undefined` (i.e. not set explicitly) - track the tree

**Comment by vakata** [comment]
I just added those events to master - I will wait for confirmation from you or @jochenberger before pushing the patch version.

**Comment by deitch** [comment]
Thanks @vakata . We will confirm via the PR and then comment back here.

@jochenberger : will comment on the PR.

**Comment by jochenberger** [comment]
@vakata It works fine with your changes, thanks. See http://jsfiddle.net/tsvr92ge/8/

**Comment by QueroBartK** [comment]
hmm is it me or does it take an awful lot of space before showing the entire text when you enable the ellipsis and resizing the column in @jochenberger latest fiddle? might be a little nitpick though.

**Comment by jochenberger** [comment]
You are right. See https://github.com/vakata/jstree/pull/1603

**Comment by deitch** [comment]
Since @vakata's considerate changes solved the problem and made the PR possible, I am closing this in favour of @jochenberger's PR #188
